/* tslint:disable */
/* eslint-disable */
/**
 * Doslano Integration API
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ,
} from '../models/index';
import {
    FromJSON,
    ToJSON,
} from '../models/index';

export interface OnLetterStatusChangedRequest {
    webhookEvent: WebhookEvent;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Если при отправке письма указан `callback_url`, мы шлём на него POST при достижении финального статуса — по каждому получателю (`recipient.sent` / `recipient.failed`) и агрегатно по письму (`letter.sent` / `letter.partial_failure` / `letter.failed` / `letter.cancelled`).  **Подпись.** Заголовок `X-Doslano-Signature: t=<unix>,v1=<hex>` — где `v1 = HMAC_SHA256(secret, \"<t>.\" + raw_body)`, `secret` — секрет аккаунта из ЛК (раздел «API»). Проверьте подпись и свежесть `t` (±5 мин).  **Доставка.** At-least-once: ждём ответ `2xx`; иначе ретраим по нарастающему графику (несколько попыток в течение ~24 ч), затем помечаем как недоставленный (видно в ЛК, можно переотправить). Дедуп — по `id` события. Порядок не гарантируется — сверяйтесь со `status` в теле. 
     * Колбек на финальный статус
     */
    async onLetterStatusChangedRaw(requestParameters: OnLetterStatusChangedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['webhookEvent'] == null) {
            throw new runtime.RequiredError(
                'webhookEvent',
                'Required parameter "webhookEvent" was null or undefined when calling onLetterStatusChanged().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/letterStatusChanged`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WebhookEventToJSON(requestParameters['webhookEvent']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Если при отправке письма указан `callback_url`, мы шлём на него POST при достижении финального статуса — по каждому получателю (`recipient.sent` / `recipient.failed`) и агрегатно по письму (`letter.sent` / `letter.partial_failure` / `letter.failed` / `letter.cancelled`).  **Подпись.** Заголовок `X-Doslano-Signature: t=<unix>,v1=<hex>` — где `v1 = HMAC_SHA256(secret, \"<t>.\" + raw_body)`, `secret` — секрет аккаунта из ЛК (раздел «API»). Проверьте подпись и свежесть `t` (±5 мин).  **Доставка.** At-least-once: ждём ответ `2xx`; иначе ретраим по нарастающему графику (несколько попыток в течение ~24 ч), затем помечаем как недоставленный (видно в ЛК, можно переотправить). Дедуп — по `id` события. Порядок не гарантируется — сверяйтесь со `status` в теле. 
     * Колбек на финальный статус
     */
    async onLetterStatusChanged(requestParameters: OnLetterStatusChangedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.onLetterStatusChangedRaw(requestParameters, initOverrides);
    }

}
