/* tslint:disable */
/* eslint-disable */
/**
 * Doslano Integration API
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateLetterRequest,
  DryRunResult,
  Letter,
  LetterStatus,
  ListLetters200Response,
  Problem,
  TrackingInfo,
} from '../models/index';
import {
    CreateLetterRequestFromJSON,
    CreateLetterRequestToJSON,
    DryRunResultFromJSON,
    DryRunResultToJSON,
    LetterFromJSON,
    LetterToJSON,
    LetterStatusFromJSON,
    LetterStatusToJSON,
    ListLetters200ResponseFromJSON,
    ListLetters200ResponseToJSON,
    ProblemFromJSON,
    ProblemToJSON,
    TrackingInfoFromJSON,
    TrackingInfoToJSON,
} from '../models/index';

export interface CreateLetterOperationRequest {
    createLetterRequest: CreateLetterRequest;
    idempotencyKey?: string;
}

export interface DownloadRecipientInventoryPdfRequest {
    id: string;
    recipientId: string;
}

export interface DownloadRecipientReceiptPdfRequest {
    id: string;
    recipientId: string;
}

export interface GetLetterRequest {
    id: string;
}

export interface GetRecipientTrackingRequest {
    id: string;
    recipientId: string;
}

export interface ListLettersRequest {
    limit?: number;
    offset?: number;
    status?: LetterStatus;
    createdFrom?: Date;
    createdTo?: Date;
}

/**
 * 
 */
export class LettersApi extends runtime.BaseAPI {

    /**
     * Создаёт и (по умолчанию) сразу оплачивает с баланса одно заказное письмо одним запросом. Опись формируется автоматически на нашей стороне.  Требуется scope `letters:write`. 
     * Отправить письмо
     */
    async createLetterRaw(requestParameters: CreateLetterOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DryRunResult>> {
        if (requestParameters['createLetterRequest'] == null) {
            throw new runtime.RequiredError(
                'createLetterRequest',
                'Required parameter "createLetterRequest" was null or undefined when calling createLetter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("apiKey", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/letters`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateLetterRequestToJSON(requestParameters['createLetterRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DryRunResultFromJSON(jsonValue));
    }

    /**
     * Создаёт и (по умолчанию) сразу оплачивает с баланса одно заказное письмо одним запросом. Опись формируется автоматически на нашей стороне.  Требуется scope `letters:write`. 
     * Отправить письмо
     */
    async createLetter(requestParameters: CreateLetterOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DryRunResult> {
        const response = await this.createLetterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Скачать PDF описи вложения (форма 107, версия отправителя) по отправлению конкретному получателю. Доступен после передачи в Почту (получатель в статусе `sent`/`delivered`); иначе `404`. Требуется scope `letters:read`.
     * PDF описи вложения получателя
     */
    async downloadRecipientInventoryPdfRaw(requestParameters: DownloadRecipientInventoryPdfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling downloadRecipientInventoryPdf().'
            );
        }

        if (requestParameters['recipientId'] == null) {
            throw new runtime.RequiredError(
                'recipientId',
                'Required parameter "recipientId" was null or undefined when calling downloadRecipientInventoryPdf().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("apiKey", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/letters/{id}/recipients/{recipient_id}/inventory.pdf`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"recipient_id"}}`, encodeURIComponent(String(requestParameters['recipientId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Скачать PDF описи вложения (форма 107, версия отправителя) по отправлению конкретному получателю. Доступен после передачи в Почту (получатель в статусе `sent`/`delivered`); иначе `404`. Требуется scope `letters:read`.
     * PDF описи вложения получателя
     */
    async downloadRecipientInventoryPdf(requestParameters: DownloadRecipientInventoryPdfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.downloadRecipientInventoryPdfRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Скачать PDF фискального чека (54-ФЗ) по отправлению конкретному получателю. Доступен, когда чек пробит и его PDF сохранён у нас (получатель в статусе `sent`/`delivered`); иначе `404`. Требуется scope `letters:read`.
     * PDF фискального чека получателя
     */
    async downloadRecipientReceiptPdfRaw(requestParameters: DownloadRecipientReceiptPdfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling downloadRecipientReceiptPdf().'
            );
        }

        if (requestParameters['recipientId'] == null) {
            throw new runtime.RequiredError(
                'recipientId',
                'Required parameter "recipientId" was null or undefined when calling downloadRecipientReceiptPdf().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("apiKey", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/letters/{id}/recipients/{recipient_id}/receipt.pdf`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"recipient_id"}}`, encodeURIComponent(String(requestParameters['recipientId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Скачать PDF фискального чека (54-ФЗ) по отправлению конкретному получателю. Доступен, когда чек пробит и его PDF сохранён у нас (получатель в статусе `sent`/`delivered`); иначе `404`. Требуется scope `letters:read`.
     * PDF фискального чека получателя
     */
    async downloadRecipientReceiptPdf(requestParameters: DownloadRecipientReceiptPdfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.downloadRecipientReceiptPdfRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Полное состояние письма с разбивкой по получателям и трек-номерами. Требуется scope `letters:read`.
     * Статус письма
     */
    async getLetterRaw(requestParameters: GetLetterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Letter>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getLetter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("apiKey", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/letters/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LetterFromJSON(jsonValue));
    }

    /**
     * Полное состояние письма с разбивкой по получателям и трек-номерами. Требуется scope `letters:read`.
     * Статус письма
     */
    async getLetter(requestParameters: GetLetterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Letter> {
        const response = await this.getLetterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * События трекинга Почты России по конкретному получателю (если трек-номер присвоен). Требуется scope `letters:read`.
     * Трек-события получателя
     */
    async getRecipientTrackingRaw(requestParameters: GetRecipientTrackingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TrackingInfo>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getRecipientTracking().'
            );
        }

        if (requestParameters['recipientId'] == null) {
            throw new runtime.RequiredError(
                'recipientId',
                'Required parameter "recipientId" was null or undefined when calling getRecipientTracking().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("apiKey", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/letters/{id}/recipients/{recipient_id}/tracking`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"recipient_id"}}`, encodeURIComponent(String(requestParameters['recipientId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TrackingInfoFromJSON(jsonValue));
    }

    /**
     * События трекинга Почты России по конкретному получателю (если трек-номер присвоен). Требуется scope `letters:read`.
     * Трек-события получателя
     */
    async getRecipientTracking(requestParameters: GetRecipientTrackingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TrackingInfo> {
        const response = await this.getRecipientTrackingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Письма аккаунта (все каналы — и API, и личный кабинет; канал указан в поле `channel`). Требуется scope `letters:read`.
     * Список писем
     */
    async listLettersRaw(requestParameters: ListLettersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListLetters200Response>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['createdFrom'] != null) {
            queryParameters['created_from'] = (requestParameters['createdFrom'] as any).toISOString();
        }

        if (requestParameters['createdTo'] != null) {
            queryParameters['created_to'] = (requestParameters['createdTo'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("apiKey", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/letters`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListLetters200ResponseFromJSON(jsonValue));
    }

    /**
     * Письма аккаунта (все каналы — и API, и личный кабинет; канал указан в поле `channel`). Требуется scope `letters:read`.
     * Список писем
     */
    async listLetters(requestParameters: ListLettersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListLetters200Response> {
        const response = await this.listLettersRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
