/* tslint:disable */
/* eslint-disable */
/**
 * Doslano Integration API
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SenderInput } from './SenderInput';
import {
    SenderInputFromJSON,
    SenderInputFromJSONTyped,
    SenderInputToJSON,
    SenderInputToJSONTyped,
} from './SenderInput';
import type { LetterContent } from './LetterContent';
import {
    LetterContentFromJSON,
    LetterContentFromJSONTyped,
    LetterContentToJSON,
    LetterContentToJSONTyped,
} from './LetterContent';
import type { LetterClass } from './LetterClass';
import {
    LetterClassFromJSON,
    LetterClassFromJSONTyped,
    LetterClassToJSON,
    LetterClassToJSONTyped,
} from './LetterClass';
import type { RecipientInput } from './RecipientInput';
import {
    RecipientInputFromJSON,
    RecipientInputFromJSONTyped,
    RecipientInputToJSON,
    RecipientInputToJSONTyped,
} from './RecipientInput';

/**
 * 
 * @export
 * @interface CreateLetterRequest
 */
export interface CreateLetterRequest {
    /**
     * Отправитель. Если не указан — берётся отправитель по умолчанию из профиля аккаунта.
     * @type {SenderInput}
     * @memberof CreateLetterRequest
     */
    sender?: SenderInput;
    /**
     * 
     * @type {Array<RecipientInput>}
     * @memberof CreateLetterRequest
     */
    recipients: Array<RecipientInput>;
    /**
     * 
     * @type {LetterContent}
     * @memberof CreateLetterRequest
     */
    content: LetterContent;
    /**
     * 
     * @type {LetterClass}
     * @memberof CreateLetterRequest
     */
    letterClass?: LetterClass;
    /**
     * Промокод (опционально).
     * @type {string}
     * @memberof CreateLetterRequest
     */
    promoCode?: string;
    /**
     * Что делать, если промокод не применился: `ignore` — отправить без
     * скидки и вернуть пометку в `pricing.promo`; `reject` — отклонить (422).
     * 
     * @type {string}
     * @memberof CreateLetterRequest
     */
    onPromoInvalid?: CreateLetterRequestOnPromoInvalidEnum;
    /**
     * Что делать при нехватке средств: `reject` — отклонить (402), письмо не
     * создаётся; `hold` — создать письмо в статусе `awaiting_payment`, оно
     * оплатится автоматически при пополнении баланса.
     * 
     * @type {string}
     * @memberof CreateLetterRequest
     */
    onInsufficientFunds?: CreateLetterRequestOnInsufficientFundsEnum;
    /**
     * HTTPS-URL для колбеков по этому письму. Если не указан — используйте поллинг.
     * @type {string}
     * @memberof CreateLetterRequest
     */
    callbackUrl?: string;
}


/**
 * @export
 */
export const CreateLetterRequestOnPromoInvalidEnum = {
    Ignore: 'ignore',
    Reject: 'reject'
} as const;
export type CreateLetterRequestOnPromoInvalidEnum = typeof CreateLetterRequestOnPromoInvalidEnum[keyof typeof CreateLetterRequestOnPromoInvalidEnum];

/**
 * @export
 */
export const CreateLetterRequestOnInsufficientFundsEnum = {
    Reject: 'reject',
    Hold: 'hold'
} as const;
export type CreateLetterRequestOnInsufficientFundsEnum = typeof CreateLetterRequestOnInsufficientFundsEnum[keyof typeof CreateLetterRequestOnInsufficientFundsEnum];


/**
 * Check if a given object implements the CreateLetterRequest interface.
 */
export function instanceOfCreateLetterRequest(value: object): value is CreateLetterRequest {
    if (!('recipients' in value) || value['recipients'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function CreateLetterRequestFromJSON(json: any): CreateLetterRequest {
    return CreateLetterRequestFromJSONTyped(json, false);
}

export function CreateLetterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateLetterRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'sender': json['sender'] == null ? undefined : SenderInputFromJSON(json['sender']),
        'recipients': ((json['recipients'] as Array<any>).map(RecipientInputFromJSON)),
        'content': LetterContentFromJSON(json['content']),
        'letterClass': json['letter_class'] == null ? undefined : LetterClassFromJSON(json['letter_class']),
        'promoCode': json['promo_code'] == null ? undefined : json['promo_code'],
        'onPromoInvalid': json['on_promo_invalid'] == null ? undefined : json['on_promo_invalid'],
        'onInsufficientFunds': json['on_insufficient_funds'] == null ? undefined : json['on_insufficient_funds'],
        'callbackUrl': json['callback_url'] == null ? undefined : json['callback_url'],
    };
}

export function CreateLetterRequestToJSON(json: any): CreateLetterRequest {
    return CreateLetterRequestToJSONTyped(json, false);
}

export function CreateLetterRequestToJSONTyped(value?: CreateLetterRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sender': SenderInputToJSON(value['sender']),
        'recipients': ((value['recipients'] as Array<any>).map(RecipientInputToJSON)),
        'content': LetterContentToJSON(value['content']),
        'letter_class': LetterClassToJSON(value['letterClass']),
        'promo_code': value['promoCode'],
        'on_promo_invalid': value['onPromoInvalid'],
        'on_insufficient_funds': value['onInsufficientFunds'],
        'callback_url': value['callbackUrl'],
    };
}

