/* tslint:disable */
/* eslint-disable */
/**
 * Doslano Integration API
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PromoResult } from './PromoResult';
import {
    PromoResultFromJSON,
    PromoResultFromJSONTyped,
    PromoResultToJSON,
    PromoResultToJSONTyped,
} from './PromoResult';

/**
 * Расчёт к списанию при реальной отправке этого запроса.
 * @export
 * @interface DryRunResultPricing
 */
export interface DryRunResultPricing {
    /**
     * Цена без скидки, в копейках.
     * @type {number}
     * @memberof DryRunResultPricing
     */
    subtotalMinor: number;
    /**
     * Итог к списанию (после промокода), в копейках. Non-binding — фиксируется при реальной оплате.
     * @type {number}
     * @memberof DryRunResultPricing
     */
    totalMinor: number;
    /**
     * 
     * @type {string}
     * @memberof DryRunResultPricing
     */
    currency: DryRunResultPricingCurrencyEnum;
    /**
     * 
     * @type {PromoResult}
     * @memberof DryRunResultPricing
     */
    promo?: PromoResult;
}


/**
 * @export
 */
export const DryRunResultPricingCurrencyEnum = {
    Rub: 'RUB'
} as const;
export type DryRunResultPricingCurrencyEnum = typeof DryRunResultPricingCurrencyEnum[keyof typeof DryRunResultPricingCurrencyEnum];


/**
 * Check if a given object implements the DryRunResultPricing interface.
 */
export function instanceOfDryRunResultPricing(value: object): value is DryRunResultPricing {
    if (!('subtotalMinor' in value) || value['subtotalMinor'] === undefined) return false;
    if (!('totalMinor' in value) || value['totalMinor'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    return true;
}

export function DryRunResultPricingFromJSON(json: any): DryRunResultPricing {
    return DryRunResultPricingFromJSONTyped(json, false);
}

export function DryRunResultPricingFromJSONTyped(json: any, ignoreDiscriminator: boolean): DryRunResultPricing {
    if (json == null) {
        return json;
    }
    return {
        
        'subtotalMinor': json['subtotal_minor'],
        'totalMinor': json['total_minor'],
        'currency': json['currency'],
        'promo': json['promo'] == null ? undefined : PromoResultFromJSON(json['promo']),
    };
}

export function DryRunResultPricingToJSON(json: any): DryRunResultPricing {
    return DryRunResultPricingToJSONTyped(json, false);
}

export function DryRunResultPricingToJSONTyped(value?: DryRunResultPricing | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subtotal_minor': value['subtotalMinor'],
        'total_minor': value['totalMinor'],
        'currency': value['currency'],
        'promo': PromoResultToJSON(value['promo']),
    };
}

