/* tslint:disable */
/* eslint-disable */
/**
 * Doslano Integration API
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  **Ограничения отправления.** При бумажной форме получения отправление содержит до 4 (четырёх) листов основного документа и лист описи вложения. Ограничение является техническим и изменению не подлежит. Материалы, не воспроизведённые на бумажном носителе, предоставляются получателю в электронной форме по коду доступа и QR-коду, размещённым на листе описи.  **Лимиты по файлам.** Формат — только PDF; до 25 МиБ на файл; к основному документу можно приложить до 49 вложений. Тело запроса — не более 64 МиБ целиком, поэтому крупные и многочисленные файлы передавайте ссылкой (`url`), а не в `base64`.  Пересылку, доставку и вручение отправлений осуществляет АО «Почта России» по договору № 3320001147-ОФ от 14 мая 2026 года; doslano оператором почтовой связи не является.  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DryRunResultPricing } from './DryRunResultPricing';
import {
    DryRunResultPricingFromJSON,
    DryRunResultPricingFromJSONTyped,
    DryRunResultPricingToJSON,
    DryRunResultPricingToJSONTyped,
} from './DryRunResultPricing';

/**
 * Результат пробного прогона (`dry_run: true`): запрос полностью
 * валиден. Письмо НЕ создано, средства НЕ списаны.
 * 
 * @export
 * @interface DryRunResult
 */
export interface DryRunResult {
    /**
     * Всегда `true` (маркер ответа пробного прогона).
     * @type {boolean}
     * @memberof DryRunResult
     */
    dryRun: boolean;
    /**
     * Всегда `true` — невалидные запросы получают 400/422.
     * @type {boolean}
     * @memberof DryRunResult
     */
    valid: boolean;
    /**
     * Количество получателей (= отправлений) в запросе.
     * @type {number}
     * @memberof DryRunResult
     */
    recipientsCount: number;
    /**
     * 
     * @type {DryRunResultPricing}
     * @memberof DryRunResult
     */
    pricing: DryRunResultPricing;
}

/**
 * Check if a given object implements the DryRunResult interface.
 */
export function instanceOfDryRunResult(value: object): value is DryRunResult {
    if (!('dryRun' in value) || value['dryRun'] === undefined) return false;
    if (!('valid' in value) || value['valid'] === undefined) return false;
    if (!('recipientsCount' in value) || value['recipientsCount'] === undefined) return false;
    if (!('pricing' in value) || value['pricing'] === undefined) return false;
    return true;
}

export function DryRunResultFromJSON(json: any): DryRunResult {
    return DryRunResultFromJSONTyped(json, false);
}

export function DryRunResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): DryRunResult {
    if (json == null) {
        return json;
    }
    return {
        
        'dryRun': json['dry_run'],
        'valid': json['valid'],
        'recipientsCount': json['recipients_count'],
        'pricing': DryRunResultPricingFromJSON(json['pricing']),
    };
}

export function DryRunResultToJSON(json: any): DryRunResult {
    return DryRunResultToJSONTyped(json, false);
}

export function DryRunResultToJSONTyped(value?: DryRunResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dry_run': value['dryRun'],
        'valid': value['valid'],
        'recipients_count': value['recipientsCount'],
        'pricing': DryRunResultPricingToJSON(value['pricing']),
    };
}

