/* tslint:disable */
/* eslint-disable */
/**
 * Doslano Integration API
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  **Ограничения отправления.** При бумажной форме получения отправление содержит до 4 (четырёх) листов основного документа и лист описи вложения. Ограничение является техническим и изменению не подлежит. Материалы, не воспроизведённые на бумажном носителе, предоставляются получателю в электронной форме по коду доступа и QR-коду, размещённым на листе описи.  **Лимиты по файлам.** Формат — только PDF; до 25 МиБ на файл; к основному документу можно приложить до 49 вложений. Тело запроса — не более 64 МиБ целиком, поэтому крупные и многочисленные файлы передавайте ссылкой (`url`), а не в `base64`.  Пересылку, доставку и вручение отправлений осуществляет АО «Почта России» по договору № 3320001147-ОФ от 14 мая 2026 года; doslano оператором почтовой связи не является.  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Источник PDF-файла. Укажите **ровно один** способ:
 * - `base64` — содержимое файла в base64 (для небольших файлов);
 * - `url` — HTTPS-ссылка, файл скачивается потоково (для крупных файлов,
 *   чтобы не передавать тело в base64).
 * Тип файла — только PDF, до 25 МиБ на файл. На бумаге печатаются до
 * 4 листов основного документа и лист описи вложения (см. описание API
 * выше).
 * 
 * @export
 * @interface FileSource
 */
export interface FileSource {
    /**
     * PDF в base64.
     * @type {string}
     * @memberof FileSource
     */
    base64?: string;
    /**
     * HTTPS-ссылка на PDF (скачиваем потоково).
     * @type {string}
     * @memberof FileSource
     */
    url?: string;
    /**
     * Имя файла (опционально, для отображения).
     * @type {string}
     * @memberof FileSource
     */
    filename?: string;
}

/**
 * Check if a given object implements the FileSource interface.
 */
export function instanceOfFileSource(value: object): value is FileSource {
    return true;
}

export function FileSourceFromJSON(json: any): FileSource {
    return FileSourceFromJSONTyped(json, false);
}

export function FileSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileSource {
    if (json == null) {
        return json;
    }
    return {
        
        'base64': json['base64'] == null ? undefined : json['base64'],
        'url': json['url'] == null ? undefined : json['url'],
        'filename': json['filename'] == null ? undefined : json['filename'],
    };
}

export function FileSourceToJSON(json: any): FileSource {
    return FileSourceToJSONTyped(json, false);
}

export function FileSourceToJSONTyped(value?: FileSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'base64': value['base64'],
        'url': value['url'],
        'filename': value['filename'],
    };
}

