/* tslint:disable */
/* eslint-disable */
/**
 * Doslano Integration API
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileSource } from './FileSource';
import {
    FileSourceFromJSON,
    FileSourceFromJSONTyped,
    FileSourceToJSON,
    FileSourceToJSONTyped,
} from './FileSource';

/**
 * Контент письма. Опись формируется автоматически.
 * @export
 * @interface LetterContent
 */
export interface LetterContent {
    /**
     * 
     * @type {FileSource}
     * @memberof LetterContent
     */
    mainFile: FileSource;
    /**
     * 
     * @type {Array<FileSource>}
     * @memberof LetterContent
     */
    attachments?: Array<FileSource>;
}

/**
 * Check if a given object implements the LetterContent interface.
 */
export function instanceOfLetterContent(value: object): value is LetterContent {
    if (!('mainFile' in value) || value['mainFile'] === undefined) return false;
    return true;
}

export function LetterContentFromJSON(json: any): LetterContent {
    return LetterContentFromJSONTyped(json, false);
}

export function LetterContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): LetterContent {
    if (json == null) {
        return json;
    }
    return {
        
        'mainFile': FileSourceFromJSON(json['main_file']),
        'attachments': json['attachments'] == null ? undefined : ((json['attachments'] as Array<any>).map(FileSourceFromJSON)),
    };
}

export function LetterContentToJSON(json: any): LetterContent {
    return LetterContentToJSONTyped(json, false);
}

export function LetterContentToJSONTyped(value?: LetterContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'main_file': FileSourceToJSON(value['mainFile']),
        'attachments': value['attachments'] == null ? undefined : ((value['attachments'] as Array<any>).map(FileSourceToJSON)),
    };
}

