/* tslint:disable */
/* eslint-disable */
/**
 * Doslano Integration API
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Жизненный цикл письма. Финальные: `sent`, `partial_failure`, `error`, `cancelled`.
 * 
 * @export
 */
export const LetterStatus = {
    Forming: 'forming',
    AwaitingPayment: 'awaiting_payment',
    Paid: 'paid',
    Sending: 'sending',
    Sent: 'sent',
    PartialFailure: 'partial_failure',
    Error: 'error',
    Cancelled: 'cancelled'
} as const;
export type LetterStatus = typeof LetterStatus[keyof typeof LetterStatus];


export function instanceOfLetterStatus(value: any): boolean {
    for (const key in LetterStatus) {
        if (Object.prototype.hasOwnProperty.call(LetterStatus, key)) {
            if (LetterStatus[key as keyof typeof LetterStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LetterStatusFromJSON(json: any): LetterStatus {
    return LetterStatusFromJSONTyped(json, false);
}

export function LetterStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): LetterStatus {
    return json as LetterStatus;
}

export function LetterStatusToJSON(value?: LetterStatus | null): any {
    return value as any;
}

export function LetterStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): LetterStatus {
    return value as LetterStatus;
}

