/* tslint:disable */
/* eslint-disable */
/**
 * Doslano Integration API
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Party } from './Party';
import {
    PartyFromJSON,
    PartyFromJSONTyped,
    PartyToJSON,
    PartyToJSONTyped,
} from './Party';
import type { PaymentResult } from './PaymentResult';
import {
    PaymentResultFromJSON,
    PaymentResultFromJSONTyped,
    PaymentResultToJSON,
    PaymentResultToJSONTyped,
} from './PaymentResult';
import type { Pricing } from './Pricing';
import {
    PricingFromJSON,
    PricingFromJSONTyped,
    PricingToJSON,
    PricingToJSONTyped,
} from './Pricing';
import type { LetterStatus } from './LetterStatus';
import {
    LetterStatusFromJSON,
    LetterStatusFromJSONTyped,
    LetterStatusToJSON,
    LetterStatusToJSONTyped,
} from './LetterStatus';
import type { Recipient } from './Recipient';
import {
    RecipientFromJSON,
    RecipientFromJSONTyped,
    RecipientToJSON,
    RecipientToJSONTyped,
} from './Recipient';

/**
 * 
 * @export
 * @interface Letter
 */
export interface Letter {
    /**
     * 
     * @type {string}
     * @memberof Letter
     */
    id: string;
    /**
     * Канал создания письма — `api` (этот API) или `web` (личный кабинет).
     * @type {string}
     * @memberof Letter
     */
    channel: LetterChannelEnum;
    /**
     * 
     * @type {LetterStatus}
     * @memberof Letter
     */
    status: LetterStatus;
    /**
     * 
     * @type {Date}
     * @memberof Letter
     */
    createdAt: Date;
    /**
     * 
     * @type {Party}
     * @memberof Letter
     */
    sender?: Party;
    /**
     * 
     * @type {Array<Recipient>}
     * @memberof Letter
     */
    recipients: Array<Recipient>;
    /**
     * 
     * @type {Pricing}
     * @memberof Letter
     */
    pricing: Pricing;
    /**
     * 
     * @type {PaymentResult}
     * @memberof Letter
     */
    payment?: PaymentResult;
    /**
     * 
     * @type {string}
     * @memberof Letter
     */
    callbackUrl?: string;
}


/**
 * @export
 */
export const LetterChannelEnum = {
    Web: 'web',
    Api: 'api'
} as const;
export type LetterChannelEnum = typeof LetterChannelEnum[keyof typeof LetterChannelEnum];


/**
 * Check if a given object implements the Letter interface.
 */
export function instanceOfLetter(value: object): value is Letter {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('channel' in value) || value['channel'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('recipients' in value) || value['recipients'] === undefined) return false;
    if (!('pricing' in value) || value['pricing'] === undefined) return false;
    return true;
}

export function LetterFromJSON(json: any): Letter {
    return LetterFromJSONTyped(json, false);
}

export function LetterFromJSONTyped(json: any, ignoreDiscriminator: boolean): Letter {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'channel': json['channel'],
        'status': LetterStatusFromJSON(json['status']),
        'createdAt': (new Date(json['created_at'])),
        'sender': json['sender'] == null ? undefined : PartyFromJSON(json['sender']),
        'recipients': ((json['recipients'] as Array<any>).map(RecipientFromJSON)),
        'pricing': PricingFromJSON(json['pricing']),
        'payment': json['payment'] == null ? undefined : PaymentResultFromJSON(json['payment']),
        'callbackUrl': json['callback_url'] == null ? undefined : json['callback_url'],
    };
}

export function LetterToJSON(json: any): Letter {
    return LetterToJSONTyped(json, false);
}

export function LetterToJSONTyped(value?: Letter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'channel': value['channel'],
        'status': LetterStatusToJSON(value['status']),
        'created_at': ((value['createdAt']).toISOString()),
        'sender': PartyToJSON(value['sender']),
        'recipients': ((value['recipients'] as Array<any>).map(RecipientToJSON)),
        'pricing': PricingToJSON(value['pricing']),
        'payment': PaymentResultToJSON(value['payment']),
        'callback_url': value['callbackUrl'],
    };
}

