/* tslint:disable */
/* eslint-disable */
/**
 * Doslano Integration API
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Тип отправления. Пока поддерживается только заказное (`registered`).
 * @export
 */
export const LetterClass = {
    Registered: 'registered'
} as const;
export type LetterClass = typeof LetterClass[keyof typeof LetterClass];


export function instanceOfLetterClass(value: any): boolean {
    for (const key in LetterClass) {
        if (Object.prototype.hasOwnProperty.call(LetterClass, key)) {
            if (LetterClass[key as keyof typeof LetterClass] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LetterClassFromJSON(json: any): LetterClass {
    return LetterClassFromJSONTyped(json, false);
}

export function LetterClassFromJSONTyped(json: any, ignoreDiscriminator: boolean): LetterClass {
    return json as LetterClass;
}

export function LetterClassToJSON(value?: LetterClass | null): any {
    return value as any;
}

export function LetterClassToJSONTyped(value: any, ignoreDiscriminator: boolean): LetterClass {
    return value as LetterClass;
}

