/* tslint:disable */
/* eslint-disable */
/**
 * Doslano Integration API
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  **Ограничения отправления.** При бумажной форме получения отправление содержит до 4 (четырёх) листов основного документа и лист описи вложения. Ограничение является техническим и изменению не подлежит. Материалы, не воспроизведённые на бумажном носителе, предоставляются получателю в электронной форме по коду доступа и QR-коду, размещённым на листе описи.  **Лимиты по файлам.** Формат — только PDF; до 25 МиБ на файл; к основному документу можно приложить до 49 вложений. Тело запроса — не более 64 МиБ целиком, поэтому крупные и многочисленные файлы передавайте ссылкой (`url`), а не в `base64`.  Пересылку, доставку и вручение отправлений осуществляет АО «Почта России» по договору № 3320001147-ОФ от 14 мая 2026 года; doslano оператором почтовой связи не является.  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Letter } from './Letter';
import {
    LetterFromJSON,
    LetterFromJSONTyped,
    LetterToJSON,
    LetterToJSONTyped,
} from './Letter';

/**
 * 
 * @export
 * @interface ListLetters200Response
 */
export interface ListLetters200Response {
    /**
     * 
     * @type {Array<Letter>}
     * @memberof ListLetters200Response
     */
    data: Array<Letter>;
    /**
     * 
     * @type {boolean}
     * @memberof ListLetters200Response
     */
    hasMore: boolean;
}

/**
 * Check if a given object implements the ListLetters200Response interface.
 */
export function instanceOfListLetters200Response(value: object): value is ListLetters200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    return true;
}

export function ListLetters200ResponseFromJSON(json: any): ListLetters200Response {
    return ListLetters200ResponseFromJSONTyped(json, false);
}

export function ListLetters200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListLetters200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(LetterFromJSON)),
        'hasMore': json['has_more'],
    };
}

export function ListLetters200ResponseToJSON(json: any): ListLetters200Response {
    return ListLetters200ResponseToJSONTyped(json, false);
}

export function ListLetters200ResponseToJSONTyped(value?: ListLetters200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(LetterToJSON)),
        'has_more': value['hasMore'],
    };
}

