/* tslint:disable */
/* eslint-disable */
/**
 * Doslano Integration API
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Тип лица — физическое или юридическое.
 * @export
 */
export const PartyType = {
    Individual: 'individual',
    Organization: 'organization'
} as const;
export type PartyType = typeof PartyType[keyof typeof PartyType];


export function instanceOfPartyType(value: any): boolean {
    for (const key in PartyType) {
        if (Object.prototype.hasOwnProperty.call(PartyType, key)) {
            if (PartyType[key as keyof typeof PartyType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PartyTypeFromJSON(json: any): PartyType {
    return PartyTypeFromJSONTyped(json, false);
}

export function PartyTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartyType {
    return json as PartyType;
}

export function PartyTypeToJSON(value?: PartyType | null): any {
    return value as any;
}

export function PartyTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): PartyType {
    return value as PartyType;
}

