/* tslint:disable */
/* eslint-disable */
/**
 * Doslano Integration API
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentResult
 */
export interface PaymentResult {
    /**
     * Списаны ли средства с баланса.
     * @type {boolean}
     * @memberof PaymentResult
     */
    charged: boolean;
    /**
     * `awaiting_payment` — при `on_insufficient_funds=hold` до пополнения.
     * @type {string}
     * @memberof PaymentResult
     */
    status?: PaymentResultStatusEnum;
}


/**
 * @export
 */
export const PaymentResultStatusEnum = {
    Paid: 'paid',
    AwaitingPayment: 'awaiting_payment'
} as const;
export type PaymentResultStatusEnum = typeof PaymentResultStatusEnum[keyof typeof PaymentResultStatusEnum];


/**
 * Check if a given object implements the PaymentResult interface.
 */
export function instanceOfPaymentResult(value: object): value is PaymentResult {
    if (!('charged' in value) || value['charged'] === undefined) return false;
    return true;
}

export function PaymentResultFromJSON(json: any): PaymentResult {
    return PaymentResultFromJSONTyped(json, false);
}

export function PaymentResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentResult {
    if (json == null) {
        return json;
    }
    return {
        
        'charged': json['charged'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function PaymentResultToJSON(json: any): PaymentResult {
    return PaymentResultToJSONTyped(json, false);
}

export function PaymentResultToJSONTyped(value?: PaymentResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'charged': value['charged'],
        'status': value['status'],
    };
}

