/* tslint:disable */
/* eslint-disable */
/**
 * Doslano Integration API
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PromoResult } from './PromoResult';
import {
    PromoResultFromJSON,
    PromoResultFromJSONTyped,
    PromoResultToJSON,
    PromoResultToJSONTyped,
} from './PromoResult';

/**
 * 
 * @export
 * @interface Pricing
 */
export interface Pricing {
    /**
     * Итоговая списанная сумма, в копейках.
     * @type {number}
     * @memberof Pricing
     */
    totalMinor: number;
    /**
     * 
     * @type {string}
     * @memberof Pricing
     */
    currency: PricingCurrencyEnum;
    /**
     * 
     * @type {PromoResult}
     * @memberof Pricing
     */
    promo?: PromoResult;
}


/**
 * @export
 */
export const PricingCurrencyEnum = {
    Rub: 'RUB'
} as const;
export type PricingCurrencyEnum = typeof PricingCurrencyEnum[keyof typeof PricingCurrencyEnum];


/**
 * Check if a given object implements the Pricing interface.
 */
export function instanceOfPricing(value: object): value is Pricing {
    if (!('totalMinor' in value) || value['totalMinor'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    return true;
}

export function PricingFromJSON(json: any): Pricing {
    return PricingFromJSONTyped(json, false);
}

export function PricingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Pricing {
    if (json == null) {
        return json;
    }
    return {
        
        'totalMinor': json['total_minor'],
        'currency': json['currency'],
        'promo': json['promo'] == null ? undefined : PromoResultFromJSON(json['promo']),
    };
}

export function PricingToJSON(json: any): Pricing {
    return PricingToJSONTyped(json, false);
}

export function PricingToJSONTyped(value?: Pricing | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_minor': value['totalMinor'],
        'currency': value['currency'],
        'promo': PromoResultToJSON(value['promo']),
    };
}

