/* tslint:disable */
/* eslint-disable */
/**
 * Doslano Integration API
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  **Ограничения отправления.** При бумажной форме получения отправление содержит до 4 (четырёх) листов основного документа и лист описи вложения. Ограничение является техническим и изменению не подлежит. Материалы, не воспроизведённые на бумажном носителе, предоставляются получателю в электронной форме по коду доступа и QR-коду, размещённым на листе описи.  **Лимиты по файлам.** Формат — только PDF; до 25 МиБ на файл; к основному документу можно приложить до 49 вложений. Тело запроса — не более 64 МиБ целиком, поэтому крупные и многочисленные файлы передавайте ссылкой (`url`), а не в `base64`.  Пересылку, доставку и вручение отправлений осуществляет АО «Почта России» по договору № 3320001147-ОФ от 14 мая 2026 года; doslano оператором почтовой связи не является.  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Результат применения промокода (если передан).
 * @export
 * @interface PromoResult
 */
export interface PromoResult {
    /**
     * 
     * @type {string}
     * @memberof PromoResult
     */
    code: string;
    /**
     * Применён ли промокод.
     * @type {boolean}
     * @memberof PromoResult
     */
    applied: boolean;
    /**
     * Размер скидки в копейках (если применён).
     * @type {number}
     * @memberof PromoResult
     */
    discountMinor?: number;
    /**
     * Пояснение, если промокод не применён (письмо при этом отправлено).
     * @type {string}
     * @memberof PromoResult
     */
    message?: string;
}

/**
 * Check if a given object implements the PromoResult interface.
 */
export function instanceOfPromoResult(value: object): value is PromoResult {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('applied' in value) || value['applied'] === undefined) return false;
    return true;
}

export function PromoResultFromJSON(json: any): PromoResult {
    return PromoResultFromJSONTyped(json, false);
}

export function PromoResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromoResult {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'applied': json['applied'],
        'discountMinor': json['discount_minor'] == null ? undefined : json['discount_minor'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function PromoResultToJSON(json: any): PromoResult {
    return PromoResultToJSONTyped(json, false);
}

export function PromoResultToJSONTyped(value?: PromoResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'applied': value['applied'],
        'discount_minor': value['discountMinor'],
        'message': value['message'],
    };
}

