/* tslint:disable */
/* eslint-disable */
/**
 * Doslano Integration API
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecipientStatus } from './RecipientStatus';
import {
    RecipientStatusFromJSON,
    RecipientStatusFromJSONTyped,
    RecipientStatusToJSON,
    RecipientStatusToJSONTyped,
} from './RecipientStatus';

/**
 * 
 * @export
 * @interface Recipient
 */
export interface Recipient {
    /**
     * 
     * @type {string}
     * @memberof Recipient
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Recipient
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Recipient
     */
    address?: string;
    /**
     * 
     * @type {RecipientStatus}
     * @memberof Recipient
     */
    status: RecipientStatus;
    /**
     * Наш трек-номер (РПО), присваивается сразу при создании.
     * @type {string}
     * @memberof Recipient
     */
    shipmentNumber?: string;
    /**
     * Трек-номер Почты России (ШПИ). Появляется после регистрации отправления.
     * @type {string}
     * @memberof Recipient
     */
    trackingNumber?: string;
    /**
     * Стоимость отправления этому получателю, в копейках.
     * @type {number}
     * @memberof Recipient
     */
    priceMinor?: number;
    /**
     * Причина ошибки (для `failed`).
     * @type {string}
     * @memberof Recipient
     */
    error?: string;
    /**
     * Письмо отправляется/отправлено на адрес, усечённый до номера дома (сработало согласие `allow_address_truncation`). Поле `address` содержит фактический адрес отправки. Отсутствие поля эквивалентно false.
     * @type {boolean}
     * @memberof Recipient
     */
    addressTruncationApplied?: boolean;
    /**
     * Ссылка на скачивание PDF фискального чека (54-ФЗ) этому получателю через наш API (см. `GET /v1/letters/{id}/recipients/{recipient_id}/receipt.pdf`). Присутствует, только когда чек пробит и его PDF сохранён у нас (получатель в статусе `sent`/`delivered`).
     * @type {string}
     * @memberof Recipient
     */
    receiptPdf?: string;
    /**
     * Ссылка на фискальный чек на сайте ОФД (1-ОФД). Присутствует, когда чек пробит (получатель `sent`/`delivered`). Может присутствовать и без `receipt_pdf` — когда наш PDF недоступен (link_only).
     * @type {string}
     * @memberof Recipient
     */
    receiptUrl?: string;
    /**
     * Ссылка на скачивание PDF описи вложения (форма 107, версия отправителя) через наш API (см. `GET /v1/letters/{id}/recipients/{recipient_id}/inventory.pdf`). Присутствует, когда опись сформирована и отправление передано в Почту (получатель в статусе `sent`/`delivered`).
     * @type {string}
     * @memberof Recipient
     */
    inventoryPdf?: string;
}



/**
 * Check if a given object implements the Recipient interface.
 */
export function instanceOfRecipient(value: object): value is Recipient {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function RecipientFromJSON(json: any): Recipient {
    return RecipientFromJSONTyped(json, false);
}

export function RecipientFromJSONTyped(json: any, ignoreDiscriminator: boolean): Recipient {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'address': json['address'] == null ? undefined : json['address'],
        'status': RecipientStatusFromJSON(json['status']),
        'shipmentNumber': json['shipment_number'] == null ? undefined : json['shipment_number'],
        'trackingNumber': json['tracking_number'] == null ? undefined : json['tracking_number'],
        'priceMinor': json['price_minor'] == null ? undefined : json['price_minor'],
        'error': json['error'] == null ? undefined : json['error'],
        'addressTruncationApplied': json['address_truncation_applied'] == null ? undefined : json['address_truncation_applied'],
        'receiptPdf': json['receipt_pdf'] == null ? undefined : json['receipt_pdf'],
        'receiptUrl': json['receipt_url'] == null ? undefined : json['receipt_url'],
        'inventoryPdf': json['inventory_pdf'] == null ? undefined : json['inventory_pdf'],
    };
}

export function RecipientToJSON(json: any): Recipient {
    return RecipientToJSONTyped(json, false);
}

export function RecipientToJSONTyped(value?: Recipient | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'address': value['address'],
        'status': RecipientStatusToJSON(value['status']),
        'shipment_number': value['shipmentNumber'],
        'tracking_number': value['trackingNumber'],
        'price_minor': value['priceMinor'],
        'error': value['error'],
        'address_truncation_applied': value['addressTruncationApplied'],
        'receipt_pdf': value['receiptPdf'],
        'receipt_url': value['receiptUrl'],
        'inventory_pdf': value['inventoryPdf'],
    };
}

