/* tslint:disable */
/* eslint-disable */
/**
 * Doslano Integration API
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PartyType } from './PartyType';
import {
    PartyTypeFromJSON,
    PartyTypeFromJSONTyped,
    PartyTypeToJSON,
    PartyTypeToJSONTyped,
} from './PartyType';

/**
 * 
 * @export
 * @interface RecipientInput
 */
export interface RecipientInput {
    /**
     * ФИО или название получателя. При resolve_address_by_inn=true ПЕРЕЗАПИСЫВАЕТСЯ наименованием из ЕГРЮЛ.
     * @type {string}
     * @memberof RecipientInput
     */
    name: string;
    /**
     * Адрес получателя (строкой; нормализуется на нашей стороне). Можно опустить при resolve_address_by_inn=true.
     * @type {string}
     * @memberof RecipientInput
     */
    address?: string;
    /**
     * 
     * @type {PartyType}
     * @memberof RecipientInput
     */
    partyType?: PartyType;
    /**
     * ИНН (10 цифр).
     * @type {string}
     * @memberof RecipientInput
     */
    inn?: string;
    /**
     * Email получателя для уведомления-копии (опционально). После отправки письма получателю на этот адрес приходит письмо со ссылкой на электронную версию (страница /receive). Пустой/опущен — уведомление не шлётся; адрес указывает отправитель и отвечает за корректность.
     * @type {string}
     * @memberof RecipientInput
     */
    email?: string;
    /**
     * Авто-резолв адреса по ИНН из ЕГРЮЛ. Работает только для party_type=organization с заданным inn: адрес и наименование берутся из реестра (DaData findById/party, головная организация), address можно не передавать. Если резолв не удался и address не передан — 422 recipient_address_unresolved; флаг без inn или не для organization — 422 recipient_resolve_requires_inn. Если передан и address — он fallback при неудаче резолва.
     * @type {boolean}
     * @memberof RecipientInput
     */
    resolveAddressByInn?: boolean;
    /**
     * Согласие на усечение адреса до номера дома, если полный адрес не проходит в Почте России (ЕПС валидирует адреса по ГАР, где помещение/офис/комната часто не зарегистрированы). Усечённая форма готовится автоматически (только когда дом распознан ФИАС). Триггеры: провал валидации адреса Почтой — проверка не блокирует письмо, пока есть варианты (административная форма → муниципальная → усечённая до дома), — и ошибка сохранения отправления SHIPMENT_ERROR — варианты перебираются сразу, без повторных попыток отправки. (Ошибка регистрации EPS_61_INVALID_ADDRESS обрабатывается независимо существующим механизмом муниципального fallback-адреса, без усечения.) Письмо, ушедшее на усечённый адрес, помечается `address_truncation_applied: true` у получателя. Если не помог ни один вариант — стандартная ошибка (422 при создании либо `failed` + возврат средств).
     * @type {boolean}
     * @memberof RecipientInput
     */
    allowAddressTruncation?: boolean;
}



/**
 * Check if a given object implements the RecipientInput interface.
 */
export function instanceOfRecipientInput(value: object): value is RecipientInput {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function RecipientInputFromJSON(json: any): RecipientInput {
    return RecipientInputFromJSONTyped(json, false);
}

export function RecipientInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipientInput {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'address': json['address'] == null ? undefined : json['address'],
        'partyType': json['party_type'] == null ? undefined : PartyTypeFromJSON(json['party_type']),
        'inn': json['inn'] == null ? undefined : json['inn'],
        'email': json['email'] == null ? undefined : json['email'],
        'resolveAddressByInn': json['resolve_address_by_inn'] == null ? undefined : json['resolve_address_by_inn'],
        'allowAddressTruncation': json['allow_address_truncation'] == null ? undefined : json['allow_address_truncation'],
    };
}

export function RecipientInputToJSON(json: any): RecipientInput {
    return RecipientInputToJSONTyped(json, false);
}

export function RecipientInputToJSONTyped(value?: RecipientInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'address': value['address'],
        'party_type': PartyTypeToJSON(value['partyType']),
        'inn': value['inn'],
        'email': value['email'],
        'resolve_address_by_inn': value['resolveAddressByInn'],
        'allow_address_truncation': value['allowAddressTruncation'],
    };
}

