/* tslint:disable */
/* eslint-disable */
/**
 * Doslano Integration API
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PartyType } from './PartyType';
import {
    PartyTypeFromJSON,
    PartyTypeFromJSONTyped,
    PartyTypeToJSON,
    PartyTypeToJSONTyped,
} from './PartyType';

/**
 * 
 * @export
 * @interface RecipientInput
 */
export interface RecipientInput {
    /**
     * ФИО или название получателя. При resolve_address_by_inn=true ПЕРЕЗАПИСЫВАЕТСЯ наименованием из ЕГРЮЛ.
     * @type {string}
     * @memberof RecipientInput
     */
    name: string;
    /**
     * Адрес получателя (строкой; нормализуется на нашей стороне). Можно опустить при resolve_address_by_inn=true.
     * @type {string}
     * @memberof RecipientInput
     */
    address?: string;
    /**
     * 
     * @type {PartyType}
     * @memberof RecipientInput
     */
    partyType?: PartyType;
    /**
     * ИНН (10 цифр).
     * @type {string}
     * @memberof RecipientInput
     */
    inn?: string;
    /**
     * Авто-резолв адреса по ИНН из ЕГРЮЛ. Работает только для party_type=organization с заданным inn: адрес и наименование берутся из реестра (DaData findById/party, головная организация), address можно не передавать. Если резолв не удался и address не передан — 422 recipient_address_unresolved; флаг без inn или не для organization — 422 recipient_resolve_requires_inn. Если передан и address — он fallback при неудаче резолва.
     * @type {boolean}
     * @memberof RecipientInput
     */
    resolveAddressByInn?: boolean;
}



/**
 * Check if a given object implements the RecipientInput interface.
 */
export function instanceOfRecipientInput(value: object): value is RecipientInput {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function RecipientInputFromJSON(json: any): RecipientInput {
    return RecipientInputFromJSONTyped(json, false);
}

export function RecipientInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipientInput {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'address': json['address'] == null ? undefined : json['address'],
        'partyType': json['party_type'] == null ? undefined : PartyTypeFromJSON(json['party_type']),
        'inn': json['inn'] == null ? undefined : json['inn'],
        'resolveAddressByInn': json['resolve_address_by_inn'] == null ? undefined : json['resolve_address_by_inn'],
    };
}

export function RecipientInputToJSON(json: any): RecipientInput {
    return RecipientInputToJSONTyped(json, false);
}

export function RecipientInputToJSONTyped(value?: RecipientInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'address': value['address'],
        'party_type': PartyTypeToJSON(value['partyType']),
        'inn': value['inn'],
        'resolve_address_by_inn': value['resolveAddressByInn'],
    };
}

