/* tslint:disable */
/* eslint-disable */
/**
 * Doslano Integration API
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  **Ограничения отправления.** При бумажной форме получения отправление содержит до 4 (четырёх) листов основного документа и лист описи вложения. Ограничение является техническим и изменению не подлежит. Материалы, не воспроизведённые на бумажном носителе, предоставляются получателю в электронной форме по коду доступа и QR-коду, размещённым на листе описи.  **Лимиты по файлам.** Формат — только PDF; до 25 МиБ на файл; к основному документу можно приложить до 49 вложений. Тело запроса — не более 64 МиБ целиком, поэтому крупные и многочисленные файлы передавайте ссылкой (`url`), а не в `base64`.  Пересылку, доставку и вручение отправлений осуществляет АО «Почта России» по договору № 3320001147-ОФ от 14 мая 2026 года; doslano оператором почтовой связи не является.  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Статус отправления получателю. `sent` — присвоен трек-номер Почты;
 * финальные: `delivered`, `failed`.
 * 
 * @export
 */
export const RecipientStatus = {
    Pending: 'pending',
    Queued: 'queued',
    Sending: 'sending',
    Sent: 'sent',
    Delivered: 'delivered',
    Failed: 'failed'
} as const;
export type RecipientStatus = typeof RecipientStatus[keyof typeof RecipientStatus];


export function instanceOfRecipientStatus(value: any): boolean {
    for (const key in RecipientStatus) {
        if (Object.prototype.hasOwnProperty.call(RecipientStatus, key)) {
            if (RecipientStatus[key as keyof typeof RecipientStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RecipientStatusFromJSON(json: any): RecipientStatus {
    return RecipientStatusFromJSONTyped(json, false);
}

export function RecipientStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipientStatus {
    return json as RecipientStatus;
}

export function RecipientStatusToJSON(value?: RecipientStatus | null): any {
    return value as any;
}

export function RecipientStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): RecipientStatus {
    return value as RecipientStatus;
}

