/* tslint:disable */
/* eslint-disable */
/**
 * Doslano Integration API
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  **Ограничения отправления.** При бумажной форме получения отправление содержит до 4 (четырёх) листов основного документа и лист описи вложения. Ограничение является техническим и изменению не подлежит. Материалы, не воспроизведённые на бумажном носителе, предоставляются получателю в электронной форме по коду доступа и QR-коду, размещённым на листе описи.  **Лимиты по файлам.** Формат — только PDF; до 25 МиБ на файл; к основному документу можно приложить до 49 вложений. Тело запроса — не более 64 МиБ целиком, поэтому крупные и многочисленные файлы передавайте ссылкой (`url`), а не в `base64`.  Пересылку, доставку и вручение отправлений осуществляет АО «Почта России» по договору № 3320001147-ОФ от 14 мая 2026 года; doslano оператором почтовой связи не является.  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PartyType } from './PartyType';
import {
    PartyTypeFromJSON,
    PartyTypeFromJSONTyped,
    PartyTypeToJSON,
    PartyTypeToJSONTyped,
} from './PartyType';

/**
 * Отправитель письма.
 * Профиль аккаунта (ЛК) достраивает отправителя ЦЕЛИКОМ или не достраивает совсем:
 * * `sender` не передан, либо в нём только `email` — имя, адрес,
 *   `party_type` и `inn` берутся из профиля. Так отправляют письма от
 *   своего имени, при необходимости переопределив почту плательщика.
 * * в `sender` передано любое из `name`, `address`, `party_type`,
 *   `inn` — отправителем считается ДРУГОЕ лицо, и все четыре поля
 *   берутся строго из запроса. `name`, `address` и `party_type` в
 *   этом режиме ОБЯЗАТЕЛЬНЫ, иначе 422 `sender_incomplete`; `inn`
 *   необязателен — не передали, значит отправитель без ИНН.
 * 
 * `party_type` обязателен намеренно: подставить за вас `individual` значило бы угадать юридическую природу лица, и «ООО «Ромашка»» без типа молча сохранилось бы физлицом.
 * Так отправляют письма от имени своих клиентов: реквизиты владельца аккаунта не подмешиваются к чужому лицу. `email` — исключение: переданный сохраняется как есть, а при отсутствии он достраивается из профиля в любом режиме, потому что это адрес плательщика для кассового чека, а не реквизит отправителя.
 * Коды отказа различают, что чинить: `sender_incomplete` — неполон запрос, `sender_profile_incomplete` — `sender` не передан, а в профиле ЛК нет имени или адреса.
 * @export
 * @interface SenderInput
 */
export interface SenderInput {
    /**
     * ФИО или название отправителя. Обязательно, если в `sender` передано хоть одно поле отправителя; иначе берётся из профиля ЛК. Строка из одних пробелов считается незаполненной.
     * @type {string}
     * @memberof SenderInput
     */
    name?: string;
    /**
     * Адрес отправителя (строкой; нормализуется). Обязателен, если в `sender` передано хоть одно поле отправителя; иначе берётся из профиля ЛК.
     * @type {string}
     * @memberof SenderInput
     */
    address?: string;
    /**
     * Email плательщика для кассового чека. Не указан — из профиля ЛК (достраивается всегда).
     * @type {string}
     * @memberof SenderInput
     */
    email?: string;
    /**
     * 
     * @type {PartyType}
     * @memberof SenderInput
     */
    partyType?: PartyType;
    /**
     * ИНН отправителя (необязателен): 10 цифр — юрлицо, 12 — физлицо или ИП. ⚠️ Если отправитель описан в запросе, ИНН из профиля НЕ подставляется: не передали — отправитель остаётся без ИНН.
     * @type {string}
     * @memberof SenderInput
     */
    inn?: string;
}



/**
 * Check if a given object implements the SenderInput interface.
 */
export function instanceOfSenderInput(value: object): value is SenderInput {
    return true;
}

export function SenderInputFromJSON(json: any): SenderInput {
    return SenderInputFromJSONTyped(json, false);
}

export function SenderInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): SenderInput {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'address': json['address'] == null ? undefined : json['address'],
        'email': json['email'] == null ? undefined : json['email'],
        'partyType': json['party_type'] == null ? undefined : PartyTypeFromJSON(json['party_type']),
        'inn': json['inn'] == null ? undefined : json['inn'],
    };
}

export function SenderInputToJSON(json: any): SenderInput {
    return SenderInputToJSONTyped(json, false);
}

export function SenderInputToJSONTyped(value?: SenderInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'address': value['address'],
        'email': value['email'],
        'party_type': PartyTypeToJSON(value['partyType']),
        'inn': value['inn'],
    };
}

