/* tslint:disable */
/* eslint-disable */
/**
 * Doslano Integration API
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PartyType } from './PartyType';
import {
    PartyTypeFromJSON,
    PartyTypeFromJSONTyped,
    PartyTypeToJSON,
    PartyTypeToJSONTyped,
} from './PartyType';

/**
 * Отправитель. Любое поле можно опустить — оно берётся из профиля аккаунта (ЛК). Например, передайте только `email`, чтобы переопределить почту плательщика для кассового чека, а имя/адрес оставить из профиля. Если `sender` не передан целиком — весь отправитель берётся из профиля.
 * @export
 * @interface SenderInput
 */
export interface SenderInput {
    /**
     * ФИО или название отправителя. Не указано — из профиля ЛК.
     * @type {string}
     * @memberof SenderInput
     */
    name?: string;
    /**
     * Адрес отправителя (строкой; нормализуется). Не указан — из профиля ЛК.
     * @type {string}
     * @memberof SenderInput
     */
    address?: string;
    /**
     * Email отправителя (плательщика) для кассового чека. Не указан — из профиля ЛК.
     * @type {string}
     * @memberof SenderInput
     */
    email?: string;
    /**
     * 
     * @type {PartyType}
     * @memberof SenderInput
     */
    partyType?: PartyType;
    /**
     * ИНН (для юр. лиц/ИП). Не указан — из профиля ЛК.
     * @type {string}
     * @memberof SenderInput
     */
    inn?: string;
}



/**
 * Check if a given object implements the SenderInput interface.
 */
export function instanceOfSenderInput(value: object): value is SenderInput {
    return true;
}

export function SenderInputFromJSON(json: any): SenderInput {
    return SenderInputFromJSONTyped(json, false);
}

export function SenderInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): SenderInput {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'address': json['address'] == null ? undefined : json['address'],
        'email': json['email'] == null ? undefined : json['email'],
        'partyType': json['party_type'] == null ? undefined : PartyTypeFromJSON(json['party_type']),
        'inn': json['inn'] == null ? undefined : json['inn'],
    };
}

export function SenderInputToJSON(json: any): SenderInput {
    return SenderInputToJSONTyped(json, false);
}

export function SenderInputToJSONTyped(value?: SenderInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'address': value['address'],
        'email': value['email'],
        'party_type': PartyTypeToJSON(value['partyType']),
        'inn': value['inn'],
    };
}

