/* tslint:disable */
/* eslint-disable */
/**
 * Doslano Integration API
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrackingInfoEventsInner } from './TrackingInfoEventsInner';
import {
    TrackingInfoEventsInnerFromJSON,
    TrackingInfoEventsInnerFromJSONTyped,
    TrackingInfoEventsInnerToJSON,
    TrackingInfoEventsInnerToJSONTyped,
} from './TrackingInfoEventsInner';

/**
 * 
 * @export
 * @interface TrackingInfo
 */
export interface TrackingInfo {
    /**
     * 
     * @type {string}
     * @memberof TrackingInfo
     */
    recipientId: string;
    /**
     * 
     * @type {string}
     * @memberof TrackingInfo
     */
    shipmentNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof TrackingInfo
     */
    trackingNumber?: string;
    /**
     * 
     * @type {Array<TrackingInfoEventsInner>}
     * @memberof TrackingInfo
     */
    events: Array<TrackingInfoEventsInner>;
}

/**
 * Check if a given object implements the TrackingInfo interface.
 */
export function instanceOfTrackingInfo(value: object): value is TrackingInfo {
    if (!('recipientId' in value) || value['recipientId'] === undefined) return false;
    if (!('events' in value) || value['events'] === undefined) return false;
    return true;
}

export function TrackingInfoFromJSON(json: any): TrackingInfo {
    return TrackingInfoFromJSONTyped(json, false);
}

export function TrackingInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackingInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'recipientId': json['recipient_id'],
        'shipmentNumber': json['shipment_number'] == null ? undefined : json['shipment_number'],
        'trackingNumber': json['tracking_number'] == null ? undefined : json['tracking_number'],
        'events': ((json['events'] as Array<any>).map(TrackingInfoEventsInnerFromJSON)),
    };
}

export function TrackingInfoToJSON(json: any): TrackingInfo {
    return TrackingInfoToJSONTyped(json, false);
}

export function TrackingInfoToJSONTyped(value?: TrackingInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recipient_id': value['recipientId'],
        'shipment_number': value['shipmentNumber'],
        'tracking_number': value['trackingNumber'],
        'events': ((value['events'] as Array<any>).map(TrackingInfoEventsInnerToJSON)),
    };
}

