/* tslint:disable */
/* eslint-disable */
/**
 * Doslano Integration API
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrackingInfoEventsInner
 */
export interface TrackingInfoEventsInner {
    /**
     * 
     * @type {string}
     * @memberof TrackingInfoEventsInner
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof TrackingInfoEventsInner
     */
    name?: string;
    /**
     * 
     * @type {Date}
     * @memberof TrackingInfoEventsInner
     */
    occurredAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof TrackingInfoEventsInner
     */
    location?: string;
}

/**
 * Check if a given object implements the TrackingInfoEventsInner interface.
 */
export function instanceOfTrackingInfoEventsInner(value: object): value is TrackingInfoEventsInner {
    return true;
}

export function TrackingInfoEventsInnerFromJSON(json: any): TrackingInfoEventsInner {
    return TrackingInfoEventsInnerFromJSONTyped(json, false);
}

export function TrackingInfoEventsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackingInfoEventsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'name': json['name'] == null ? undefined : json['name'],
        'occurredAt': json['occurred_at'] == null ? undefined : (new Date(json['occurred_at'])),
        'location': json['location'] == null ? undefined : json['location'],
    };
}

export function TrackingInfoEventsInnerToJSON(json: any): TrackingInfoEventsInner {
    return TrackingInfoEventsInnerToJSONTyped(json, false);
}

export function TrackingInfoEventsInnerToJSONTyped(value?: TrackingInfoEventsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'name': value['name'],
        'occurred_at': value['occurredAt'] == null ? undefined : ((value['occurredAt']).toISOString()),
        'location': value['location'],
    };
}

