/* tslint:disable */
/* eslint-disable */
/**
 * Doslano Integration API
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebhookEventData } from './WebhookEventData';
import {
    WebhookEventDataFromJSON,
    WebhookEventDataFromJSONTyped,
    WebhookEventDataToJSON,
    WebhookEventDataToJSONTyped,
} from './WebhookEventData';

/**
 * 
 * @export
 * @interface WebhookEvent
 */
export interface WebhookEvent {
    /**
     * Уникальный идентификатор события (для дедупа).
     * @type {string}
     * @memberof WebhookEvent
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookEvent
     */
    type: WebhookEventTypeEnum;
    /**
     * 
     * @type {Date}
     * @memberof WebhookEvent
     */
    createdAt: Date;
    /**
     * 
     * @type {WebhookEventData}
     * @memberof WebhookEvent
     */
    data: WebhookEventData;
}


/**
 * @export
 */
export const WebhookEventTypeEnum = {
    LetterSent: 'letter.sent',
    LetterPartialFailure: 'letter.partial_failure',
    LetterFailed: 'letter.failed',
    LetterCancelled: 'letter.cancelled',
    RecipientSent: 'recipient.sent',
    RecipientFailed: 'recipient.failed',
    RecipientDelivered: 'recipient.delivered'
} as const;
export type WebhookEventTypeEnum = typeof WebhookEventTypeEnum[keyof typeof WebhookEventTypeEnum];


/**
 * Check if a given object implements the WebhookEvent interface.
 */
export function instanceOfWebhookEvent(value: object): value is WebhookEvent {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function WebhookEventFromJSON(json: any): WebhookEvent {
    return WebhookEventFromJSONTyped(json, false);
}

export function WebhookEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'createdAt': (new Date(json['created_at'])),
        'data': WebhookEventDataFromJSON(json['data']),
    };
}

export function WebhookEventToJSON(json: any): WebhookEvent {
    return WebhookEventToJSONTyped(json, false);
}

export function WebhookEventToJSONTyped(value?: WebhookEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'created_at': ((value['createdAt']).toISOString()),
        'data': WebhookEventDataToJSON(value['data']),
    };
}

