/* tslint:disable */
/* eslint-disable */
/**
 * Doslano Integration API
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookEventData
 */
export interface WebhookEventData {
    /**
     * 
     * @type {string}
     * @memberof WebhookEventData
     */
    letterId: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookEventData
     */
    recipientId?: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookEventData
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookEventData
     */
    shipmentNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookEventData
     */
    trackingNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookEventData
     */
    error?: string;
}

/**
 * Check if a given object implements the WebhookEventData interface.
 */
export function instanceOfWebhookEventData(value: object): value is WebhookEventData {
    if (!('letterId' in value) || value['letterId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function WebhookEventDataFromJSON(json: any): WebhookEventData {
    return WebhookEventDataFromJSONTyped(json, false);
}

export function WebhookEventDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookEventData {
    if (json == null) {
        return json;
    }
    return {
        
        'letterId': json['letter_id'],
        'recipientId': json['recipient_id'] == null ? undefined : json['recipient_id'],
        'status': json['status'],
        'shipmentNumber': json['shipment_number'] == null ? undefined : json['shipment_number'],
        'trackingNumber': json['tracking_number'] == null ? undefined : json['tracking_number'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function WebhookEventDataToJSON(json: any): WebhookEventData {
    return WebhookEventDataToJSONTyped(json, false);
}

export function WebhookEventDataToJSONTyped(value?: WebhookEventData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'letter_id': value['letterId'],
        'recipient_id': value['recipientId'],
        'status': value['status'],
        'shipment_number': value['shipmentNumber'],
        'tracking_number': value['trackingNumber'],
        'error': value['error'],
    };
}

